import Head from "next/head";
import Header from "../components/Header";
import Home from "../components/Home";
import requests from "../utils/requests";

export default function App({ popularResults, trendingResults }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="bg-transparent">
        <Home
          popularResults={popularResults}
          trendingResults={trendingResults}
        />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const [popularRes, trendingRes] = await Promise.all([
    fetch(`https://api.themoviedb.org/3${requests.fetchPopular.url.tv}`),
    fetch(`https://api.themoviedb.org/3${requests.fetchTrending.url}`),
  ]);

  const [popular, trending] = await Promise.all([
    popularRes.json(),
    trendingRes.json(),
  ]);

  return {
    props: {
      popularResults: popular.results,
      trendingResults: trending.results,
    },
  };
}
